<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\Models\Administration\Municipality;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('adm_municipalities', function (Blueprint $table) 
        {
            $table->id();
            $table->string('name');
            $table->boolean('active')->default(true);
            $table->unsignedBigInteger('adm_department_id');
            $table->foreign('adm_department_id')->references('id')->on('adm_departments');
            $table->timestamp('created_at', 0)->useCurrent();
            $table->timestamp('updated_at', 0)->useCurrent();
            $table->softDeletes();

            $table->unique(['name', 'adm_department_id'])->whereNull('deleted_at');
        });

        DB::transaction(function () {
            Municipality::create(['name' => 'Alegría', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Berlín', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'California', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Concepción Batres', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'El Triunfo', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Ereguayquín', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Estanzuelas', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Jiquilisco', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Jucuapa', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Jucuarán', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Mercedes Umaña', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Nueva Granada', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Ozatlán', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Puerto El Triunfo', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'San Agustín', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'San Buenaventura', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'San Dionisio', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'San Francisco Javier', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Santa Elena', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Santa María', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Santiago de María', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Tecapán', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Usulután', 'adm_department_id' => 1]);
            Municipality::create(['name' => 'Santa Ana', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Candelaria de la Frontera', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Chalchuapa', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Coatepeque', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'El Congo', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'El Porvenir', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Masahuat', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Metapán', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'San Antonio Pajonal', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'San Sebastián Salitrillo', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Santa Rosa Guachipilín', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Santiago de la Frontera', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Texistepeque', 'adm_department_id' => 2]);
            Municipality::create(['name' => 'Sensuntepeque', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Cinquera', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Dolores', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Guacotecti', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Ilobasco ', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Jutiapa', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'San Isidro', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Tejutepeque', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Victoria', 'adm_department_id' => 3]);
            Municipality::create(['name' => 'Ahuachapán', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Apaneca', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Atiquizaya', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Concepción de Ataco', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'El Refugio', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Guaymango', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Jujutla', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'San Francisco Menéndez', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'San Lorenzo', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'San Pedro Puxtla', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Tacuba', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Turín', 'adm_department_id' => 4]);
            Municipality::create(['name' => 'Chalatenango', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Agua Caliente', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Arcatao', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Azacualpa', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Cancasque', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Citalá', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Comalapa', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Concepción Quezaltepeque', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Dulce Nombre de María', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'El Carrizal', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'El Paraíso', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'La Laguna', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'La Palma', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'La Reina', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Las Flores', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Las Vueltas', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Nombre de Jesús', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Nueva Concepción', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Nueva Trinidad', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Ojos de Agua', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Potonico', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Antonio de la Cruz', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Antonio Los Ranchos', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Fernando', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Francisco Lempa', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Francisco Morazán', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Ignacio', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Isidro Labrador', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Luis del Carmen', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Miguel de Mercedes', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'San Rafael', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Santa Rita', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Tejutla', 'adm_department_id' => 5]);
            Municipality::create(['name' => 'Cojutepeque', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Candelaria', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'El Carmen', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'El Rosario', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Monte San Juan', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Oratorio de Concepción', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'San Bartolomé Perulapía', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'San Cristóbal', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'San José Guayabal', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'San Pedro Perulapán', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'San Rafael Cedros', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'San Ramón', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Santa Cruz Analquito', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Santa Cruz Michapa', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Suchitoto', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Tenancingo', 'adm_department_id' => 6]);
            Municipality::create(['name' => 'Zacatecoluca', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Cuyultitán', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'El Rosario', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Jerusalén', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Mercedes La Ceiba', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Olocuilta', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Paraíso de Osorio', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Antonio Masahuat', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Emigdio', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Francisco Chinameca', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Pedro Masahuat', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Juan Nonualco', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Juan Talpa', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Juan Tepezontes', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Luis La Herradura', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Luis Talpa', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Miguel Tepezontes', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Pedro Nonualco', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'San Rafael Obrajuelo', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Santa María Ostuma', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Santiago Nonualco', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Tapalhuaca', 'adm_department_id' => 7]);
            Municipality::create(['name' => 'Santa Tecla', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Antiguo Cuscatlán', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Chiltiupán', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Ciudad Arce', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Colón', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Comasagua', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Huizúcar', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Jayaque', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Jicalapa', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'La Libertad', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Nuevo Cuscatlán', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Quezaltepeque', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'San Juan Opico', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Sacacoyo', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'San José Villanueva', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'San Matías', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'San Pablo Tacachico', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Talnique', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Tamanique', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Teotepeque', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Tepecoyo', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Zaragoza', 'adm_department_id' => 8]);
            Municipality::create(['name' => 'Sonsonate', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Acajutla', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Armenia', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Caluco', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Cuisnahuat', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Izalco', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Juayúa', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Nahuizalco', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Nahulingo', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Salcoatitán', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'San Antonio del Monte', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'San Julián', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Santa Catarina Masahuat', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Santa Isabel Ishuatán', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Santo Domingo de Guzmán', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'Sonzacate', 'adm_department_id' => 9]);
            Municipality::create(['name' => 'San Salvador ', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Aguilares', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Apopa', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Ayutuxtepeque', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Cuscatancingo', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Delgado', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'El Paisnal', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Guazapa', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Ilopango', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Mejicanos', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Nejapa', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Panchimalco', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Rosario de Mora', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'San Marcos', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'San Martín', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Santiago Texacuangos', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Santo Tomás', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Soyapango', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'Tonacatepeque', 'adm_department_id' => 10]);
            Municipality::create(['name' => 'San Vicente', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Apastepeque', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Guadalupe', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'San Cayetano Istepeque', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'San Esteban Catarina', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'San Ildefonso', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'San Lorenzo', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'San Sebastián', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Santa Clara', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Santo Domingo', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Tecoluca', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Tepetitán', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'Verapaz', 'adm_department_id' => 11]);
            Municipality::create(['name' => 'San Miguel ', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Carolina', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Chapeltique', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Chinameca', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Chirilagua', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Ciudad Barrios', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Comacarán', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'El Tránsito', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Lolotique', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Moncagua', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Nueva Guadalupe', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Nuevo Edén de San Juan', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Quelepa', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'San Antonio', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'San Gerardo', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'San Jorge', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'San Luis de la Reina', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'San Rafael Oriente', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Sesori', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'Uluazapa', 'adm_department_id' => 12]);
            Municipality::create(['name' => 'San Francisco Gotera', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Arambala', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Cacaopera', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Chilanga', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Corinto', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Delicias de Concepción', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'El Divisadero', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'El Rosario', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Gualococti', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Guatajiagua', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Joateca', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Jocoaitique', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Jocoro', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Lolotiquillo', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Meanguera', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Osicala', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Perquín', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'San Carlos', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'San Fernando', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'San Isidro', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'San Simón', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Sensembra', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Sociedad', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Torola', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Yamabal', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'Yoloaiquín', 'adm_department_id' => 13]);
            Municipality::create(['name' => 'La Unión', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Anamorós', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Bolívar', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Concepción de Oriente', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Conchagua', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'El Carmen', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'El Sauce', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Intipucá', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Lislique', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Meanguera del Golfo', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Nueva Esparta', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Pasaquina', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Polorós', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'San Alejo', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'San José', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Santa Rosa de Lima', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Yayantique', 'adm_department_id' => 14]);
            Municipality::create(['name' => 'Yucuaiquín', 'adm_department_id' => 14]);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('adm_municipalities');
    }
};
